// <auto-generated />
using System;
using Collectivite.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collectivite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251102220617_LiaisonExerciceBudgetPrimitif")]
    partial class LiaisonExerciceBudgetPrimitif
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Collectivite.Models.BudgetLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetPrimitifId")
                        .HasColumnType("int");

                    b.Property<int>("MontantActu")
                        .HasColumnType("int");

                    b.Property<int>("MontantPrevu")
                        .HasColumnType("int");

                    b.Property<int>("NommenclatureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetPrimitifId");

                    b.HasIndex("NommenclatureId");

                    b.ToTable("BudgetLines");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetPrimitif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommuneId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateVote")
                        .HasColumnType("date");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<int>("Montant")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommuneId");

                    b.HasIndex("ExerciceId")
                        .IsUnique();

                    b.ToTable("BudgetsPrimitifs");
                });

            modelBuilder.Entity("Collectivite.Models.Commune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Communes");
                });

            modelBuilder.Entity("Collectivite.Models.Exercice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommuneId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date");

                    b.Property<bool>("EstCloture")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CommuneId");

                    b.ToTable("Exercices");
                });

            modelBuilder.Entity("Collectivite.Models.Nommenclature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Chapitre")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Nature")
                        .HasColumnType("int");

                    b.Property<string>("Paragraphe")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<string>("SousParagraphe")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Nommenclatures");
                });

            modelBuilder.Entity("Collectivite.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommuneId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CommuneId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetLine", b =>
                {
                    b.HasOne("Collectivite.Models.BudgetPrimitif", "BudgetPrimitif")
                        .WithMany("BudgetLines")
                        .HasForeignKey("BudgetPrimitifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Nommenclature", "Nommenclature")
                        .WithMany()
                        .HasForeignKey("NommenclatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetPrimitif");

                    b.Navigation("Nommenclature");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetPrimitif", b =>
                {
                    b.HasOne("Collectivite.Models.Commune", null)
                        .WithMany("BudgetsPrimitifs")
                        .HasForeignKey("CommuneId");

                    b.HasOne("Collectivite.Models.Exercice", "Exercice")
                        .WithOne("BudgetPrimitif")
                        .HasForeignKey("Collectivite.Models.BudgetPrimitif", "ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");
                });

            modelBuilder.Entity("Collectivite.Models.Exercice", b =>
                {
                    b.HasOne("Collectivite.Models.Commune", null)
                        .WithMany("Exercices")
                        .HasForeignKey("CommuneId");
                });

            modelBuilder.Entity("Collectivite.Models.Nommenclature", b =>
                {
                    b.HasOne("Collectivite.Models.Nommenclature", "Parent")
                        .WithMany("Enfants")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Collectivite.Models.User", b =>
                {
                    b.HasOne("Collectivite.Models.Commune", "Commune")
                        .WithMany("Users")
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commune");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetPrimitif", b =>
                {
                    b.Navigation("BudgetLines");
                });

            modelBuilder.Entity("Collectivite.Models.Commune", b =>
                {
                    b.Navigation("BudgetsPrimitifs");

                    b.Navigation("Exercices");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Collectivite.Models.Exercice", b =>
                {
                    b.Navigation("BudgetPrimitif");
                });

            modelBuilder.Entity("Collectivite.Models.Nommenclature", b =>
                {
                    b.Navigation("Enfants");
                });
#pragma warning restore 612, 618
        }
    }
}
