// <auto-generated />
using System;
using Collectivite.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collectivite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211131250_DeleteMotifToMandat")]
    partial class DeleteMotifToMandat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Collectivite.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Collectivite.Models.BonCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExpressionBesoinId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExpressionBesoinId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("BonCommandes");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetPrimitifId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantActu")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MontantEntreSortie")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MontantPrevu")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MontantRealise")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("NommenclatureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetPrimitifId");

                    b.HasIndex("NommenclatureId");

                    b.ToTable("BudgetLines");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetPrimitif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateApprobation")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateValidation")
                        .HasColumnType("date");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FichierValidation")
                        .HasColumnType("longblob");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<decimal>("MontantDepense")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MontantRecette")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciceId")
                        .IsUnique();

                    b.ToTable("BudgetsPrimitifs");
                });

            modelBuilder.Entity("Collectivite.Models.Commune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommuneType")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date");

                    b.Property<double>("DistanceCapitale")
                        .HasColumnType("double");

                    b.Property<double>("DistanceChefLieuProvince")
                        .HasColumnType("double");

                    b.Property<double>("DistanceChefLieuRegion")
                        .HasColumnType("double");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prefecture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Communes");
                });

            modelBuilder.Entity("Collectivite.Models.CompteBancaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BIC")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Banque")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TiersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BIC")
                        .IsUnique();

                    b.HasIndex("IBAN")
                        .IsUnique();

                    b.HasIndex("TiersId");

                    b.ToTable("CompteBancaires");
                });

            modelBuilder.Entity("Collectivite.Models.CompteComptable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContrePartieId")
                        .HasColumnType("int");

                    b.Property<string>("IntituleCompte")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroCompte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContrePartieId");

                    b.ToTable("CompteComptables");
                });

            modelBuilder.Entity("Collectivite.Models.Contrats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateEcheance")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateSignature")
                        .HasColumnType("date");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FichierJoin")
                        .HasColumnType("longblob");

                    b.Property<double>("MontantContrat")
                        .HasColumnType("double");

                    b.Property<string>("NumeroContrat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TiersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciceId");

                    b.HasIndex("TiersId");

                    b.ToTable("Contrats");
                });

            modelBuilder.Entity("Collectivite.Models.DetailBonCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonCommandeId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PrixUnitaire")
                        .HasColumnType("double");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeId");

                    b.ToTable("DetailsBonCommandes");
                });

            modelBuilder.Entity("Collectivite.Models.DetailCommune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Densite")
                        .HasColumnType("double");

                    b.Property<int>("EffectifPermanent")
                        .HasColumnType("int");

                    b.Property<int>("EffectifTemporaire")
                        .HasColumnType("int");

                    b.Property<int>("EffectifTotalPersonnel")
                        .HasColumnType("int");

                    b.Property<int>("IdCommune")
                        .HasColumnType("int");

                    b.Property<int>("NombreAssociation")
                        .HasColumnType("int");

                    b.Property<int>("NombreCentresSante")
                        .HasColumnType("int");

                    b.Property<int>("NombreClassesCollege")
                        .HasColumnType("int");

                    b.Property<int>("NombreClassesLycee")
                        .HasColumnType("int");

                    b.Property<int>("NombreClassesPrescolaire")
                        .HasColumnType("int");

                    b.Property<int>("NombreClassesPrimaire")
                        .HasColumnType("int");

                    b.Property<int>("NombreConseillers")
                        .HasColumnType("int");

                    b.Property<int>("NombreCooperatives")
                        .HasColumnType("int");

                    b.Property<int>("NombreDelegationSpeciale")
                        .HasColumnType("int");

                    b.Property<int>("NombreDetenteursArmesFeu")
                        .HasColumnType("int");

                    b.Property<int>("NombreDistricts")
                        .HasColumnType("int");

                    b.Property<int>("NombreEcoles")
                        .HasColumnType("int");

                    b.Property<int>("NombreEcolesCollege")
                        .HasColumnType("int");

                    b.Property<int>("NombreEcolesLycee")
                        .HasColumnType("int");

                    b.Property<int>("NombreEcolesPrescolaire")
                        .HasColumnType("int");

                    b.Property<int>("NombreEcolesPrimaire")
                        .HasColumnType("int");

                    b.Property<int>("NombreElevesCollege")
                        .HasColumnType("int");

                    b.Property<int>("NombreElevesLycee")
                        .HasColumnType("int");

                    b.Property<int>("NombreElevesPrescolaire")
                        .HasColumnType("int");

                    b.Property<int>("NombreElevesPrimaire")
                        .HasColumnType("int");

                    b.Property<int>("NombreForages")
                        .HasColumnType("int");

                    b.Property<int>("NombreGroupements")
                        .HasColumnType("int");

                    b.Property<int>("NombreMarches")
                        .HasColumnType("int");

                    b.Property<int>("NombreMarchesHebdomadaires")
                        .HasColumnType("int");

                    b.Property<int>("NombreMarchesJournaliers")
                        .HasColumnType("int");

                    b.Property<int>("NombreOng")
                        .HasColumnType("int");

                    b.Property<int>("NombreOngEtrangeres")
                        .HasColumnType("int");

                    b.Property<int>("NombreOngNationales")
                        .HasColumnType("int");

                    b.Property<int>("NombrePointsEau")
                        .HasColumnType("int");

                    b.Property<int>("NombrePostesSante")
                        .HasColumnType("int");

                    b.Property<int>("NombreQuartiers")
                        .HasColumnType("int");

                    b.Property<int>("NombreSanteAmelioree")
                        .HasColumnType("int");

                    b.Property<int>("NombreSecteurs")
                        .HasColumnType("int");

                    b.Property<int>("PopulationFemmes")
                        .HasColumnType("int");

                    b.Property<int>("PopulationHommes")
                        .HasColumnType("int");

                    b.Property<int>("PopulationTotale")
                        .HasColumnType("int");

                    b.Property<double>("Superficie")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdCommune");

                    b.ToTable("DetailCommunes");
                });

            modelBuilder.Entity("Collectivite.Models.DetailExpressionBesoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExpressionBesoinId")
                        .HasColumnType("int");

                    b.Property<int>("NommenclatureId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpressionBesoinId");

                    b.HasIndex("NommenclatureId");

                    b.ToTable("DetailExpressionBesoins");
                });

            modelBuilder.Entity("Collectivite.Models.DetailsFacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FactureId")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<double>("MontantTotal")
                        .HasColumnType("double");

                    b.Property<double>("PrixUnitaire")
                        .HasColumnType("double");

                    b.Property<double>("Quantite")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.ToTable("DetailsFactures");
                });

            modelBuilder.Entity("Collectivite.Models.DocumentTiers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateEmission")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Extension")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsValide")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroDocument")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("TailleFichier")
                        .HasColumnType("bigint");

                    b.Property<int>("TiersId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TiersId");

                    b.ToTable("DocumentTiers");
                });

            modelBuilder.Entity("Collectivite.Models.EcritureComptable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompteCreditId")
                        .HasColumnType("int");

                    b.Property<int>("CompteDebitId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateEcriture")
                        .HasColumnType("date");

                    b.Property<int?>("MandatId")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("MouvementId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdreRecetteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompteCreditId");

                    b.HasIndex("CompteDebitId");

                    b.HasIndex("MandatId");

                    b.HasIndex("MouvementId");

                    b.HasIndex("OrdreRecetteId");

                    b.ToTable("EcritureComptables");
                });

            modelBuilder.Entity("Collectivite.Models.Engagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BonCommandeId")
                        .HasColumnType("int");

                    b.Property<int>("BudgetLineId")
                        .HasColumnType("int");

                    b.Property<int>("CommuneId")
                        .HasColumnType("int");

                    b.Property<int?>("ContratId")
                        .HasColumnType("int");

                    b.Property<decimal>("CreditsBudgetaires")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DateEngagement")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("EngagementsAnterieurs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<int?>("FactureId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FichierJoin")
                        .HasColumnType("longblob");

                    b.Property<string>("FichierName")
                        .HasColumnType("longtext");

                    b.Property<decimal>("MontantEngagement")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MontantLettre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TiersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeId");

                    b.HasIndex("BudgetLineId");

                    b.HasIndex("CommuneId");

                    b.HasIndex("ContratId");

                    b.HasIndex("ExerciceId");

                    b.HasIndex("FactureId");

                    b.HasIndex("TiersId");

                    b.ToTable("Engagements");
                });

            modelBuilder.Entity("Collectivite.Models.Exercice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date");

                    b.Property<bool>("EstCloture")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IdDetailCommune")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdDetailCommune")
                        .IsUnique();

                    b.ToTable("Exercices");
                });

            modelBuilder.Entity("Collectivite.Models.ExpressionBesoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciceId");

                    b.ToTable("ExpressionBesoins");
                });

            modelBuilder.Entity("Collectivite.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContratId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FichierJoin")
                        .HasColumnType("longblob");

                    b.Property<double>("MontantHT")
                        .HasColumnType("double");

                    b.Property<double>("MontantTTC")
                        .HasColumnType("double");

                    b.Property<string>("NumeroFacture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TauxTVA")
                        .HasColumnType("double");

                    b.Property<int>("TiersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContratId");

                    b.HasIndex("ExerciceId");

                    b.HasIndex("TiersId");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("Collectivite.Models.Mandat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AutresPrecomptes")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Bordereau")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DatePaiement")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EngagementId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FichierJoin")
                        .HasColumnType("longblob");

                    b.Property<sbyte?>("FichierName")
                        .HasColumnType("tinyint");

                    b.Property<int>("Mois")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantBrut")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MontantLettre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("MontantNet")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NumeroMandat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Rts")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .IsUnique();

                    b.ToTable("Mandats");
                });

            modelBuilder.Entity("Collectivite.Models.Mouvement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<byte[]>("FichierJoint")
                        .HasColumnType("longblob");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NumBanqueBenef")
                        .HasColumnType("longtext");

                    b.Property<string>("RefChèque")
                        .HasColumnType("longtext");

                    b.Property<string>("RefVirement")
                        .HasColumnType("longtext");

                    b.Property<int>("idCompteComptable")
                        .HasColumnType("int");

                    b.Property<int?>("idMandat")
                        .HasColumnType("int");

                    b.Property<int?>("idOrdreRecette")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idCompteComptable");

                    b.HasIndex("idMandat");

                    b.HasIndex("idOrdreRecette");

                    b.ToTable("mouvement", (string)null);
                });

            modelBuilder.Entity("Collectivite.Models.Nommenclature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Chapitre")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Nature")
                        .HasColumnType("int");

                    b.Property<string>("Paragraphe")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<string>("SousParagraphe")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Nommenclatures");
                });

            modelBuilder.Entity("Collectivite.Models.OrdreRecette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetLineId")
                        .HasColumnType("int");

                    b.Property<int>("CommuneId")
                        .HasColumnType("int");

                    b.Property<string>("Comptable")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOrdre")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantOrdre")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MontantOrdreLettre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Motifs")
                        .HasColumnType("text");

                    b.Property<string>("NumeroOrdre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TiersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetLineId");

                    b.HasIndex("CommuneId");

                    b.HasIndex("ExerciceId");

                    b.HasIndex("TiersId");

                    b.ToTable("OrdreRecettes");
                });

            modelBuilder.Entity("Collectivite.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Collectivite.Models.Recensement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetLineId")
                        .HasColumnType("int");

                    b.Property<int>("CommuneId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<double>("MontantRecense")
                        .HasColumnType("double");

                    b.Property<int>("TiersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetLineId");

                    b.HasIndex("CommuneId");

                    b.HasIndex("ExerciceId");

                    b.HasIndex("TiersId");

                    b.ToTable("Recensements");
                });

            modelBuilder.Entity("Collectivite.Models.Remaniement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdBudgetLine")
                        .HasColumnType("int");

                    b.Property<double>("Montant")
                        .HasColumnType("double");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<int>("TypeRemaniement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdBudgetLine");

                    b.ToTable("Remaniements");
                });

            modelBuilder.Entity("Collectivite.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Collectivite.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Collectivite.Models.Tiers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Categorie")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActif")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nif")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroPieceIdentite")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroTva")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RaisonSociale")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Rccm")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SecteurActivite")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("TypePieceIdentite")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nif");

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("Collectivite.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommuneId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CommuneId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Collectivite.Models.BonCommande", b =>
                {
                    b.HasOne("Collectivite.Models.ExpressionBesoin", "ExpressionBesoin")
                        .WithMany()
                        .HasForeignKey("ExpressionBesoinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpressionBesoin");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetLine", b =>
                {
                    b.HasOne("Collectivite.Models.BudgetPrimitif", "BudgetPrimitif")
                        .WithMany("BudgetLines")
                        .HasForeignKey("BudgetPrimitifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Nommenclature", "Nommenclature")
                        .WithMany()
                        .HasForeignKey("NommenclatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetPrimitif");

                    b.Navigation("Nommenclature");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetPrimitif", b =>
                {
                    b.HasOne("Collectivite.Models.Exercice", "Exercice")
                        .WithOne("BudgetPrimitif")
                        .HasForeignKey("Collectivite.Models.BudgetPrimitif", "ExerciceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercice");
                });

            modelBuilder.Entity("Collectivite.Models.CompteBancaire", b =>
                {
                    b.HasOne("Collectivite.Models.Tiers", "Tiers")
                        .WithMany("CompteBancaires")
                        .HasForeignKey("TiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Collectivite.Models.CompteComptable", b =>
                {
                    b.HasOne("Collectivite.Models.CompteComptable", "ContrePartie")
                        .WithMany("SousComptes")
                        .HasForeignKey("ContrePartieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContrePartie");
                });

            modelBuilder.Entity("Collectivite.Models.Contrats", b =>
                {
                    b.HasOne("Collectivite.Models.Exercice", "Exercice")
                        .WithMany("Contrats")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Tiers", "Tiers")
                        .WithMany("Contrats")
                        .HasForeignKey("TiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Collectivite.Models.DetailBonCommande", b =>
                {
                    b.HasOne("Collectivite.Models.BonCommande", "BonCommande")
                        .WithMany("Details")
                        .HasForeignKey("BonCommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonCommande");
                });

            modelBuilder.Entity("Collectivite.Models.DetailCommune", b =>
                {
                    b.HasOne("Collectivite.Models.Commune", "Commune")
                        .WithMany("DetailCommunes")
                        .HasForeignKey("IdCommune")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commune");
                });

            modelBuilder.Entity("Collectivite.Models.DetailExpressionBesoin", b =>
                {
                    b.HasOne("Collectivite.Models.ExpressionBesoin", "ExpressionBesoin")
                        .WithMany("Details")
                        .HasForeignKey("ExpressionBesoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Nommenclature", "Nommenclature")
                        .WithMany()
                        .HasForeignKey("NommenclatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpressionBesoin");

                    b.Navigation("Nommenclature");
                });

            modelBuilder.Entity("Collectivite.Models.DetailsFacture", b =>
                {
                    b.HasOne("Collectivite.Models.Facture", "Facture")
                        .WithMany("Details")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("Collectivite.Models.DocumentTiers", b =>
                {
                    b.HasOne("Collectivite.Models.Tiers", "Tiers")
                        .WithMany("Documents")
                        .HasForeignKey("TiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Collectivite.Models.EcritureComptable", b =>
                {
                    b.HasOne("Collectivite.Models.CompteComptable", "CompteCredit")
                        .WithMany()
                        .HasForeignKey("CompteCreditId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.CompteComptable", "CompteDebit")
                        .WithMany()
                        .HasForeignKey("CompteDebitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Mandat", "Mandat")
                        .WithMany("EcritureComptables")
                        .HasForeignKey("MandatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collectivite.Models.Mouvement", "Mouvement")
                        .WithMany()
                        .HasForeignKey("MouvementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collectivite.Models.OrdreRecette", "OrdreRecette")
                        .WithMany("EcritureComptables")
                        .HasForeignKey("OrdreRecetteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CompteCredit");

                    b.Navigation("CompteDebit");

                    b.Navigation("Mandat");

                    b.Navigation("Mouvement");

                    b.Navigation("OrdreRecette");
                });

            modelBuilder.Entity("Collectivite.Models.Engagement", b =>
                {
                    b.HasOne("Collectivite.Models.BonCommande", "BonCommande")
                        .WithMany("Engagements")
                        .HasForeignKey("BonCommandeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Collectivite.Models.BudgetLine", "BudgetLine")
                        .WithMany("Engagements")
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Commune", "Commune")
                        .WithMany("Engagements")
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Contrats", "Contrat")
                        .WithMany("Engagements")
                        .HasForeignKey("ContratId");

                    b.HasOne("Collectivite.Models.Exercice", "Exercice")
                        .WithMany("Engagements")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Facture", "Facture")
                        .WithMany("Engagements")
                        .HasForeignKey("FactureId");

                    b.HasOne("Collectivite.Models.Tiers", "Tiers")
                        .WithMany("Engagements")
                        .HasForeignKey("TiersId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BonCommande");

                    b.Navigation("BudgetLine");

                    b.Navigation("Commune");

                    b.Navigation("Contrat");

                    b.Navigation("Exercice");

                    b.Navigation("Facture");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Collectivite.Models.Exercice", b =>
                {
                    b.HasOne("Collectivite.Models.DetailCommune", "DetailCommune")
                        .WithOne("Exercice")
                        .HasForeignKey("Collectivite.Models.Exercice", "IdDetailCommune")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DetailCommune");
                });

            modelBuilder.Entity("Collectivite.Models.ExpressionBesoin", b =>
                {
                    b.HasOne("Collectivite.Models.Exercice", "Exercice")
                        .WithMany()
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercice");
                });

            modelBuilder.Entity("Collectivite.Models.Facture", b =>
                {
                    b.HasOne("Collectivite.Models.Contrats", "Contrats")
                        .WithMany("Factures")
                        .HasForeignKey("ContratId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collectivite.Models.Exercice", "Exercice")
                        .WithMany()
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Tiers", "Tiers")
                        .WithMany("Factures")
                        .HasForeignKey("TiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrats");

                    b.Navigation("Exercice");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Collectivite.Models.Mandat", b =>
                {
                    b.HasOne("Collectivite.Models.Engagement", "Engagement")
                        .WithOne("Mandat")
                        .HasForeignKey("Collectivite.Models.Mandat", "EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engagement");
                });

            modelBuilder.Entity("Collectivite.Models.Mouvement", b =>
                {
                    b.HasOne("Collectivite.Models.CompteComptable", "CompteComptable")
                        .WithMany()
                        .HasForeignKey("idCompteComptable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Mandat", "Mandat")
                        .WithMany()
                        .HasForeignKey("idMandat")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Collectivite.Models.OrdreRecette", "OrdreRecette")
                        .WithMany()
                        .HasForeignKey("idOrdreRecette")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CompteComptable");

                    b.Navigation("Mandat");

                    b.Navigation("OrdreRecette");
                });

            modelBuilder.Entity("Collectivite.Models.Nommenclature", b =>
                {
                    b.HasOne("Collectivite.Models.Nommenclature", "Parent")
                        .WithMany("Enfants")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Collectivite.Models.OrdreRecette", b =>
                {
                    b.HasOne("Collectivite.Models.BudgetLine", "BudgetLine")
                        .WithMany()
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Commune", "Commune")
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Exercice", "Exercice")
                        .WithMany()
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Tiers", "Tiers")
                        .WithMany()
                        .HasForeignKey("TiersId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BudgetLine");

                    b.Navigation("Commune");

                    b.Navigation("Exercice");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Collectivite.Models.Recensement", b =>
                {
                    b.HasOne("Collectivite.Models.BudgetLine", "BudgetLine")
                        .WithMany("Recensements")
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Commune", "Commune")
                        .WithMany("Recensements")
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Exercice", "Exercice")
                        .WithMany("Recensements")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Tiers", "Tiers")
                        .WithMany("Recensements")
                        .HasForeignKey("TiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetLine");

                    b.Navigation("Commune");

                    b.Navigation("Exercice");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Collectivite.Models.Remaniement", b =>
                {
                    b.HasOne("Collectivite.Models.BudgetLine", "BudgetLine")
                        .WithMany("Remaniements")
                        .HasForeignKey("IdBudgetLine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetLine");
                });

            modelBuilder.Entity("Collectivite.Models.RolePermission", b =>
                {
                    b.HasOne("Collectivite.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Collectivite.Models.User", b =>
                {
                    b.HasOne("Collectivite.Models.Commune", "Commune")
                        .WithMany("Users")
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commune");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Collectivite.Models.BonCommande", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Engagements");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetLine", b =>
                {
                    b.Navigation("Engagements");

                    b.Navigation("Recensements");

                    b.Navigation("Remaniements");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetPrimitif", b =>
                {
                    b.Navigation("BudgetLines");
                });

            modelBuilder.Entity("Collectivite.Models.Commune", b =>
                {
                    b.Navigation("DetailCommunes");

                    b.Navigation("Engagements");

                    b.Navigation("Recensements");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Collectivite.Models.CompteComptable", b =>
                {
                    b.Navigation("SousComptes");
                });

            modelBuilder.Entity("Collectivite.Models.Contrats", b =>
                {
                    b.Navigation("Engagements");

                    b.Navigation("Factures");
                });

            modelBuilder.Entity("Collectivite.Models.DetailCommune", b =>
                {
                    b.Navigation("Exercice");
                });

            modelBuilder.Entity("Collectivite.Models.Engagement", b =>
                {
                    b.Navigation("Mandat");
                });

            modelBuilder.Entity("Collectivite.Models.Exercice", b =>
                {
                    b.Navigation("BudgetPrimitif");

                    b.Navigation("Contrats");

                    b.Navigation("Engagements");

                    b.Navigation("Recensements");
                });

            modelBuilder.Entity("Collectivite.Models.ExpressionBesoin", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Collectivite.Models.Facture", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Engagements");
                });

            modelBuilder.Entity("Collectivite.Models.Mandat", b =>
                {
                    b.Navigation("EcritureComptables");
                });

            modelBuilder.Entity("Collectivite.Models.Nommenclature", b =>
                {
                    b.Navigation("Enfants");
                });

            modelBuilder.Entity("Collectivite.Models.OrdreRecette", b =>
                {
                    b.Navigation("EcritureComptables");
                });

            modelBuilder.Entity("Collectivite.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Collectivite.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Collectivite.Models.Tiers", b =>
                {
                    b.Navigation("CompteBancaires");

                    b.Navigation("Contrats");

                    b.Navigation("Documents");

                    b.Navigation("Engagements");

                    b.Navigation("Factures");

                    b.Navigation("Recensements");
                });
#pragma warning restore 612, 618
        }
    }
}
