// <auto-generated />
using System;
using Collectivite.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collectivite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Collectivite.Models.BudgetLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetPrimitifId")
                        .HasColumnType("int");

                    b.Property<int>("MontantPrevu")
                        .HasColumnType("int");

                    b.Property<int>("NommenclatureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetPrimitifId");

                    b.HasIndex("NommenclatureId");

                    b.ToTable("BudgetLines");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetPrimitif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateVote")
                        .HasColumnType("date");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<int>("Montant")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciceId")
                        .IsUnique();

                    b.ToTable("BudgetsPrimitifs");
                });

            modelBuilder.Entity("Collectivite.Models.Commune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date");

                    b.Property<double>("DistanceCapitale")
                        .HasColumnType("double");

                    b.Property<double>("DistanceChefLieuProvince")
                        .HasColumnType("double");

                    b.Property<double>("DistanceChefLieuRegion")
                        .HasColumnType("double");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Communes");
                });

            modelBuilder.Entity("Collectivite.Models.DetailCommune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Densite")
                        .HasColumnType("double");

                    b.Property<int>("EffectifPermanent")
                        .HasColumnType("int");

                    b.Property<int>("EffectifTemporaire")
                        .HasColumnType("int");

                    b.Property<int>("EffectifTotalPersonnel")
                        .HasColumnType("int");

                    b.Property<int>("IdCommune")
                        .HasColumnType("int");

                    b.Property<int>("NombreCentresSante")
                        .HasColumnType("int");

                    b.Property<int>("NombreClassesPrimaires")
                        .HasColumnType("int");

                    b.Property<int>("NombreClassesSecondaires")
                        .HasColumnType("int");

                    b.Property<int>("NombreConseillers")
                        .HasColumnType("int");

                    b.Property<int>("NombreCooperatives")
                        .HasColumnType("int");

                    b.Property<int>("NombreDelegationSpeciale")
                        .HasColumnType("int");

                    b.Property<int>("NombreDetenteursArmesFeu")
                        .HasColumnType("int");

                    b.Property<int>("NombreDistricts")
                        .HasColumnType("int");

                    b.Property<int>("NombreEcoles")
                        .HasColumnType("int");

                    b.Property<int>("NombreEcolesPrimaires")
                        .HasColumnType("int");

                    b.Property<int>("NombreEcolesSecondaires")
                        .HasColumnType("int");

                    b.Property<int>("NombreElevesPrimaires")
                        .HasColumnType("int");

                    b.Property<int>("NombreElevesSecondaires")
                        .HasColumnType("int");

                    b.Property<int>("NombreForages")
                        .HasColumnType("int");

                    b.Property<int>("NombreGroupements")
                        .HasColumnType("int");

                    b.Property<int>("NombreMarches")
                        .HasColumnType("int");

                    b.Property<int>("NombreMarchesHebdomadaires")
                        .HasColumnType("int");

                    b.Property<int>("NombreMarchesJournaliers")
                        .HasColumnType("int");

                    b.Property<int>("NombreOng")
                        .HasColumnType("int");

                    b.Property<int>("NombreOngEtrangeres")
                        .HasColumnType("int");

                    b.Property<int>("NombreOngNationales")
                        .HasColumnType("int");

                    b.Property<int>("NombreQuartiers")
                        .HasColumnType("int");

                    b.Property<int>("NombreSecteurs")
                        .HasColumnType("int");

                    b.Property<int>("PopulationFemmes")
                        .HasColumnType("int");

                    b.Property<int>("PopulationHommes")
                        .HasColumnType("int");

                    b.Property<int>("PopulationTotale")
                        .HasColumnType("int");

                    b.Property<double>("Superficie")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdCommune");

                    b.ToTable("DetailCommunes");
                });

            modelBuilder.Entity("Collectivite.Models.Exercice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date");

                    b.Property<bool>("EstCloture")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdDetailCommune")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdDetailCommune")
                        .IsUnique();

                    b.ToTable("Exercices");
                });

            modelBuilder.Entity("Collectivite.Models.Nommenclature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Chapitre")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Nature")
                        .HasColumnType("int");

                    b.Property<string>("Paragraphe")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<string>("SousParagraphe")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Nommenclatures");
                });

            modelBuilder.Entity("Collectivite.Models.Remaniement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdBudgetLine")
                        .HasColumnType("int");

                    b.Property<double>("Montant")
                        .HasColumnType("double");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeRemaniement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdBudgetLine");

                    b.ToTable("Remaniements");
                });

            modelBuilder.Entity("Collectivite.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommuneId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CommuneId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetLine", b =>
                {
                    b.HasOne("Collectivite.Models.BudgetPrimitif", "BudgetPrimitif")
                        .WithMany("BudgetLines")
                        .HasForeignKey("BudgetPrimitifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectivite.Models.Nommenclature", "Nommenclature")
                        .WithMany()
                        .HasForeignKey("NommenclatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetPrimitif");

                    b.Navigation("Nommenclature");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetPrimitif", b =>
                {
                    b.HasOne("Collectivite.Models.Exercice", "Exercice")
                        .WithOne("BudgetPrimitif")
                        .HasForeignKey("Collectivite.Models.BudgetPrimitif", "ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");
                });

            modelBuilder.Entity("Collectivite.Models.DetailCommune", b =>
                {
                    b.HasOne("Collectivite.Models.Commune", "Commune")
                        .WithMany("DetailCommunes")
                        .HasForeignKey("IdCommune")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commune");
                });

            modelBuilder.Entity("Collectivite.Models.Exercice", b =>
                {
                    b.HasOne("Collectivite.Models.DetailCommune", "DetailCommune")
                        .WithOne("Exercice")
                        .HasForeignKey("Collectivite.Models.Exercice", "IdDetailCommune")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetailCommune");
                });

            modelBuilder.Entity("Collectivite.Models.Nommenclature", b =>
                {
                    b.HasOne("Collectivite.Models.Nommenclature", "Parent")
                        .WithMany("Enfants")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Collectivite.Models.Remaniement", b =>
                {
                    b.HasOne("Collectivite.Models.BudgetLine", "BudgetLine")
                        .WithMany("Remaniements")
                        .HasForeignKey("IdBudgetLine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetLine");
                });

            modelBuilder.Entity("Collectivite.Models.User", b =>
                {
                    b.HasOne("Collectivite.Models.Commune", "Commune")
                        .WithMany("Users")
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commune");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetLine", b =>
                {
                    b.Navigation("Remaniements");
                });

            modelBuilder.Entity("Collectivite.Models.BudgetPrimitif", b =>
                {
                    b.Navigation("BudgetLines");
                });

            modelBuilder.Entity("Collectivite.Models.Commune", b =>
                {
                    b.Navigation("DetailCommunes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Collectivite.Models.DetailCommune", b =>
                {
                    b.Navigation("Exercice");
                });

            modelBuilder.Entity("Collectivite.Models.Exercice", b =>
                {
                    b.Navigation("BudgetPrimitif");
                });

            modelBuilder.Entity("Collectivite.Models.Nommenclature", b =>
                {
                    b.Navigation("Enfants");
                });
#pragma warning restore 612, 618
        }
    }
}
